name: yo_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+5
  floor: ^0.12.0
  connectivity: ^0.4.6+1
  firebase_auth: ^0.15.3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.0+1
  flutter_cache_manager: ^1.2.2
  phone_number: ^0.6.0+2
  share: ^0.6.4
  url_launcher: ^5.4.5
  contacts_service: ^0.4.4
  permission_handler: ^5.0.0+hotfix.4
  intl: ^0.16.1
  image_picker: ^0.6.5+2
  flutter_svg: ^0.17.1
  cupertino_icons: ^0.1.2
  image_cropper: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.12.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
  assets:
    - assets/
